# Generated by Django 4.2.29 on 2026-03-30 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/%Y/%m/",
                        verbose_name="头像",
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="个人简介"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
            },
        ),
        migrations.CreateModel(
            name="ImageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_image",
                    models.ImageField(
                        upload_to="uploads/%Y/%m/%d/", verbose_name="上传图片"
                    ),
                ),
                (
                    "upload_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="上传时间"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小 (字节)"),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="原始文件名"
                    ),
                ),
                (
                    "detection_status",
                    models.CharField(
                        choices=[
                            ("pending", "待检测"),
                            ("completed", "已完成"),
                            ("failed", "检测失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="检测状态",
                    ),
                ),
                (
                    "detection_mode",
                    models.CharField(
                        choices=[
                            ("all", "全物品检测"),
                            ("laptop_only", "仅笔记本检测"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="检测模式",
                    ),
                ),
                (
                    "result_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="results/%Y/%m/%d/",
                        verbose_name="识别结果图片",
                    ),
                ),
                (
                    "detection_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="检测时间"
                    ),
                ),
                (
                    "total_objects",
                    models.IntegerField(default=0, verbose_name="物品总数"),
                ),
                (
                    "detection_data",
                    models.JSONField(blank=True, default=dict, verbose_name="检测数据"),
                ),
                (
                    "processing_time",
                    models.FloatField(default=0.0, verbose_name="处理耗时"),
                ),
                (
                    "selected_models",
                    models.JSONField(
                        blank=True, default=list, verbose_name="选择的模型"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "图片记录",
                "verbose_name_plural": "图片记录",
                "ordering": ["-upload_time"],
            },
        ),
    ]
